### PR TITLE
Add montreal event

### PR DESCRIPTION
**Pull request by patcon**
@millette Bonjour!

Please do let me know if you have any corrections or changes you would like made. (I'm sorry that the website isn't currently bilingual, but we'd be 100% happy to merge any pull requests, if anyone in Montreal could help us out with that!)

We're attempting to move the website toward a community-maintained model -- let me know if you'd appreciate push access :)

cc: @gabesawhney

### CODE REVIEW

**Comment by patcon** [comment]
I'll merge this by end-of-day tomorrow, but if you don't catch this in time, then we can easily do any fixups :)

**Comment by millette** [comment]
Oh, thanks! But it's not a hackathon! Still looking for presenters to settle on a format. Might turn out to be a sort of barcamp, we'll see.

**Comment by patcon** [comment]
Thanks! Assuming you would appreciate it being listed, just poke me as soon as it's settled enough to post something, and we'll get it merged ;)

**Comment by millette** [comment]
Thanks, yes! I will link back to http://codeacross.ca/ as well in a few minutes.

I would remove the word "Barcamp" from the listing, sorry for the confusion. When I saw the PR the first time, I noticed the words "hackfest", and I known that's how ODD started, but I'm not really sure about our format yet, so best leave it open.

It's OK to merge/publish after that. Thank you very much :-)

**Comment by patcon** [comment]
Thanks! I'll merge.

**Pull request merged**
